/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.project.quiz.screens;

import com.project.quiz.database_connectivity.ConnectionClass;

/**
 *
 * @author 91987
 */
public class SplashScreen extends javax.swing.JFrame {

    
     static SplashScreen sc = new SplashScreen();
    /**
     * Creates new form LoginScreen
     */
    public SplashScreen() {
        initComponents();
        ConnectionClass.getInstance();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        progressBar = new javax.swing.JProgressBar();
        loginImage = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        progressBar.setForeground(new java.awt.Color(0, 204, 255));
        getContentPane().add(progressBar);
        progressBar.setBounds(70, 440, 540, 20);

        loginImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\91987\\Downloads\\quizLoginImage.png")); // NOI18N
        getContentPane().add(loginImage);
        loginImage.setBounds(-270, -100, 920, 690);

        progressLabel.setText("jLabel1");
        getContentPane().add(progressLabel);
        progressLabel.setBounds(320, 470, 38, 16);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                sc.setVisible(true);
            }
            
        });
        
        try {
            for(int i=0;i<=100;i++) {
                Thread.sleep(100);
                sc.progressBar.setValue(i);
                if(i==5) {
                   sc.progressLabel.setText("Loading,Please wait.....");
                }
                if(i == 50){
                   sc.progressLabel.setText("Almost there....");
                }
                if(i==100){
//                    AddAdmin addAdmin=new AddAdmin();
//                    addAdmin.setVisible(true);
                    //ViewUsers viewUsers = new ViewUsers();
                   // viewUsers.setVisible(true);
                    LogInScreen loginScreen = new LogInScreen();
                    loginScreen.setVisible(true);
                    sc.dispose();
                }
            }
        } catch (InterruptedException e) {
            System.out.println("Error in Splash Screen = " + e);
        }
        

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loginImage;
    private java.awt.PopupMenu popupMenu1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel progressLabel;
    // End of variables declaration//GEN-END:variables
}
